# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dougs_TV_console(object):
    def setupUi(self, Dougs_TV_console):
        Dougs_TV_console.setObjectName("Dougs_TV_console")
        Dougs_TV_console.resize(600, 700)
        Dougs_TV_console.setMinimumSize(QtCore.QSize(600, 700))
        Dougs_TV_console.setMaximumSize(QtCore.QSize(600, 700))
        self.centralwidget = QtWidgets.QWidget(parent=Dougs_TV_console)
        self.centralwidget.setObjectName("centralwidget")
        self.volume_display = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.volume_display.setGeometry(QtCore.QRect(420, 380, 100, 75))
        self.volume_display.setObjectName("volume_display")
        self.channel_display = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.channel_display.setGeometry(QtCore.QRect(80, 380, 100, 75))
        self.channel_display.setObjectName("channel_display")
        self.channel_up_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.channel_up_button.setGeometry(QtCore.QRect(80, 490, 100, 50))
        self.channel_up_button.setObjectName("channel_up_button")
        self.channel_down_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.channel_down_button.setGeometry(QtCore.QRect(80, 570, 100, 50))
        self.channel_down_button.setObjectName("channel_down_button")
        self.power_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.power_button.setGeometry(QtCore.QRect(250, 490, 100, 50))
        self.power_button.setObjectName("power_button")
        self.mute_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mute_button.setGeometry(QtCore.QRect(250, 570, 100, 50))
        self.mute_button.setObjectName("mute_button")
        self.volume_up_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volume_up_button.setGeometry(QtCore.QRect(420, 490, 100, 50))
        self.volume_up_button.setObjectName("volume_up_button")
        self.volume_down_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volume_down_button.setGeometry(QtCore.QRect(420, 570, 100, 50))
        self.volume_down_button.setObjectName("volume_down_button")
        self.TV_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.TV_display.setGeometry(QtCore.QRect(25, 30, 550, 331))
        self.TV_display.setText("")
        self.TV_display.setPixmap(QtGui.QPixmap("black.jpg"))
        self.TV_display.setScaledContents(True)
        self.TV_display.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TV_display.setObjectName("TV_display")
        Dougs_TV_console.setCentralWidget(self.centralwidget)

        self.retranslateUi(Dougs_TV_console)
        QtCore.QMetaObject.connectSlotsByName(Dougs_TV_console)

    def retranslateUi(self, Dougs_TV_console):
        _translate = QtCore.QCoreApplication.translate
        Dougs_TV_console.setWindowTitle(_translate("Dougs_TV_console", "Doug\'s TV Console"))
        self.channel_up_button.setText(_translate("Dougs_TV_console", "Channel Up"))
        self.channel_down_button.setText(_translate("Dougs_TV_console", "Channel Down"))
        self.power_button.setText(_translate("Dougs_TV_console", "Power"))
        self.mute_button.setText(_translate("Dougs_TV_console", "Mute"))
        self.volume_up_button.setText(_translate("Dougs_TV_console", "volume up"))
        self.volume_down_button.setText(_translate("Dougs_TV_console", "Volume down"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dougs_TV_console = QtWidgets.QMainWindow()
    ui = Ui_Dougs_TV_console()
    ui.setupUi(Dougs_TV_console)
    Dougs_TV_console.show()
    sys.exit(app.exec())
